#!/usr/bin/env bash
cat _md/metadata.md _md/overview.md _md/getting_started.md _md/usage.md _md/api.md _md/credits.md > LiteStore_UserGuide.md
hastyscribe LiteStore_UserGuide.md
rm LiteStore_UserGuide.md
